-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'e2ceab32b4cdfca0' HASH '8c4a53014fa62280e6505c11a510e19d1accf8f680977f4187ba0d5d72c63a89' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."INGREDIENT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 15) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "QUANTITY" FLOAT(53),
    "UNIT" CHARACTER VARYING(255),
    "RECIPE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."INGREDIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");    
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.INGREDIENT;               
INSERT INTO "PUBLIC"."INGREDIENT" VALUES
(1, 'Pizza dough', 1.0, 'ball', 1),
(2, 'Tomato sauce', 150.0, 'ml', 1),
(3, 'Mozzarella', 200.0, 'g', 1),
(4, 'Fresh basil', 10.0, 'leaves', 1),
(11, 'carrot', 1.0, 'kg', 3),
(12, 'salt', 10.0, 'g', 3),
(13, 'vinegar', 100.0, 'g', 3);           
CREATE CACHED TABLE "PUBLIC"."RECIPE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(1000),
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PREP_TIME_MINUTES" INTEGER,
    "SERVINGS" INTEGER,
    "INSTRUCTIONS" CHARACTER VARYING
);         
ALTER TABLE "PUBLIC"."RECIPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.RECIPE;   
INSERT INTO "PUBLIC"."RECIPE" VALUES
(1, 'Classic Italian pizza with tomato, mozzarella and basil.', 'Margherita Pizza', 30, 4, U&'Preheat oven to 250C with a pizza stone if you have one.Stretch the dough into a round base.\000a        Spread the tomato sauce evenly, leaving a border for the crust.\000a        Tear the mozzarella and scatter it over the sauce.\000a        Bake for 8-10 minutes until the crust is golden.\000a        Top with fresh basil leaves right before serving.'),
(3, '"korean" spicy carrot from immigrants in the USSR', 'spicy carrot', 60, 10, U&'Step 1: add a little of this\000aStep 2: add a little of that\000aStep 3: mix it all together\000aStep 4: voil\00e0');            
ALTER TABLE "PUBLIC"."INGREDIENT" ADD CONSTRAINT "PUBLIC"."FKJ0S4YWMQQQW4H5IOMMIGH5YJA" FOREIGN KEY("RECIPE_ID") REFERENCES "PUBLIC"."RECIPE"("ID") NOCHECK;   
